/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param platform 
 * @param title 
 * @param priceCents 
 * @param origin Origin marker for the UI badge.
 * @param state 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance.
 * @param imageUrl 
 * @param listingUrl 
 * @param visualSim CLIP cosine [0,1]; populated after the visual-rank pass.
 */

data class CreateMagicScanResponseTopHits (

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "priceCents")
    val priceCents: java.math.BigDecimal,

    /* Origin marker for the UI badge. */
    @Json(name = "origin")
    val origin: kotlin.String,

    /* 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance. */
    @Json(name = "state")
    val state: CreateMagicScanResponseTopHits.State,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,

    @Json(name = "listingUrl")
    val listingUrl: kotlin.String? = null,

    /* CLIP cosine [0,1]; populated after the visual-rank pass. */
    @Json(name = "visualSim")
    val visualSim: java.math.BigDecimal? = null

) {

    /**
     * 'active' = currently for sale; 'sold' = historical comp. UI  renders distinct badges so the seller can see both at a glance.
     *
     * Values: active,sold
     */
    enum class State(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "sold") sold("sold");
    }
}

