/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.CreateInventoryCsvImportResponseProblems

import com.squareup.moshi.Json

/**
 * 
 *
 * @param problems 
 * @param problemCount 
 * @param maxRows 
 * @param created 
 * @param updated 
 * @param usable Rows that mapped cleanly. `created + updated` when not a dry run.
 * @param totalRows 
 * @param listingsCreated 
 * @param dryRun True when nothing was written — a preview pass.
 */

data class CreateInventoryCsvImportResponse (

    @Json(name = "problems")
    val problems: kotlin.collections.List<CreateInventoryCsvImportResponseProblems>,

    @Json(name = "problemCount")
    val problemCount: java.math.BigDecimal,

    @Json(name = "maxRows")
    val maxRows: java.math.BigDecimal,

    @Json(name = "created")
    val created: java.math.BigDecimal,

    @Json(name = "updated")
    val updated: java.math.BigDecimal,

    /* Rows that mapped cleanly. `created + updated` when not a dry run. */
    @Json(name = "usable")
    val usable: java.math.BigDecimal,

    @Json(name = "totalRows")
    val totalRows: java.math.BigDecimal,

    @Json(name = "listingsCreated")
    val listingsCreated: java.math.BigDecimal,

    /* True when nothing was written — a preview pass. */
    @Json(name = "dryRun")
    val dryRun: kotlin.Boolean

)

