/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.CreateCbxRevenueSweepResponseBreakdown

import com.squareup.moshi.Json

/**
 * 
 *
 * @param swept 
 * @param baseUnits 
 * @param txSig 
 * @param reason 
 * @param breakdown 
 */

data class CreateCbxRevenueSweepResponse (

    @Json(name = "swept")
    val swept: kotlin.Boolean,

    @Json(name = "baseUnits")
    val baseUnits: kotlin.String,

    @Json(name = "txSig")
    val txSig: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "breakdown")
    val breakdown: CreateCbxRevenueSweepResponseBreakdown? = null

)

