/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param status 
 * @param platformListingId 
 * @param buyerUserId 
 * @param amountCents 
 * @param message 
 */

data class CreateBuyerOfferResponseDataOffer (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "platformListingId")
    val platformListingId: kotlin.String,

    @Json(name = "buyerUserId")
    val buyerUserId: kotlin.String,

    @Json(name = "amountCents")
    val amountCents: java.math.BigDecimal,

    @Json(name = "message")
    val message: kotlin.String? = null

)

