/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.CreateBuyerIdentifyResponseHudAction
import net.crossly.models.CreateBuyerIdentifyResponseHudFacts

import com.squareup.moshi.Json

/**
 * 
 *
 * @param headline 
 * @param facts 
 * @param action 
 * @param tone `win` earned a saving, `info` found something, `none` found nothing.
 * @param subline 
 * @param imageUrl Image for the lens card, when there is a match worth showing.
 */

data class CreateBuyerIdentifyResponseHud (

    @Json(name = "headline")
    val headline: kotlin.String,

    @Json(name = "facts")
    val facts: kotlin.collections.List<CreateBuyerIdentifyResponseHudFacts>,

    @Json(name = "action")
    val action: CreateBuyerIdentifyResponseHudAction,

    /* `win` earned a saving, `info` found something, `none` found nothing. */
    @Json(name = "tone")
    val tone: CreateBuyerIdentifyResponseHud.Tone,

    @Json(name = "subline")
    val subline: kotlin.String? = null,

    /* Image for the lens card, when there is a match worth showing. */
    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null

) {

    /**
     * `win` earned a saving, `info` found something, `none` found nothing.
     *
     * Values: none,info,win
     */
    enum class Tone(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "info") info("info"),
        @Json(name = "win") win("win");
    }
}

