/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param updated 
 * @param skipped Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch.
 */

data class CreateOrderBulkMarkShippedResponse (

    @Json(name = "updated")
    val updated: java.math.BigDecimal,

    /* Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch. */
    @Json(name = "skipped")
    val skipped: java.math.BigDecimal

)

