/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetAutomationRuleExportResponseAction
import net.crossly.models.GetAutomationRuleExportResponseCondition
import net.crossly.models.GetAutomationRuleExportResponseMetadata

import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param action 
 * @param trigger 
 * @param schemaVersion 
 * @param condition 
 * @param metadata 
 * @param description 
 * @param platforms 
 * @param dollarSchema Optional reference to the public schema URL — purely cosmetic.
 */

data class GetAutomationRuleExportByIdResponse (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "action")
    val action: GetAutomationRuleExportResponseAction,

    @Json(name = "trigger")
    val trigger: GetAutomationRuleExportResponseAction,

    @Json(name = "schemaVersion")
    val schemaVersion: java.math.BigDecimal,

    @Json(name = "condition")
    val condition: GetAutomationRuleExportResponseCondition? = null,

    @Json(name = "metadata")
    val metadata: GetAutomationRuleExportResponseMetadata? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "platforms")
    val platforms: kotlin.collections.List<kotlin.String>? = null,

    /* Optional reference to the public schema URL — purely cosmetic. */
    @Json(name = "\$schema")
    val dollarSchema: kotlin.String? = null

)

