/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetAutomationRuleExportResponseRecipes

import com.squareup.moshi.Json

/**
 * 
 *
 * @param dollarSchema 
 * @param schemaVersion 
 * @param exportedAt 
 * @param recipes 
 */

data class GetAutomationRuleExportResponse (

    @Json(name = "\$schema")
    val dollarSchema: kotlin.String,

    @Json(name = "schemaVersion")
    val schemaVersion: java.math.BigDecimal,

    @Json(name = "exportedAt")
    val exportedAt: kotlin.String,

    @Json(name = "recipes")
    val recipes: kotlin.collections.List<GetAutomationRuleExportResponseRecipes>

)

