/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param spendCents 
 * @param mediaCostCents 
 * @param managementFeeCents 
 * @param impressions 
 * @param clicks 
 * @param conversions 
 * @param attributedRevenueCents 
 * @param spilloverConversions 
 * @param spilloverRevenueCents 
 * @param returnBps 
 * @param enabled 
 * @param autoPausedAt 
 * @param autoPausedReason 
 */

data class GetAdOffsiteReportResponse (

    @Json(name = "spendCents")
    val spendCents: java.math.BigDecimal,

    @Json(name = "mediaCostCents")
    val mediaCostCents: java.math.BigDecimal,

    @Json(name = "managementFeeCents")
    val managementFeeCents: java.math.BigDecimal,

    @Json(name = "impressions")
    val impressions: java.math.BigDecimal,

    @Json(name = "clicks")
    val clicks: java.math.BigDecimal,

    @Json(name = "conversions")
    val conversions: java.math.BigDecimal,

    @Json(name = "attributedRevenueCents")
    val attributedRevenueCents: java.math.BigDecimal,

    @Json(name = "spilloverConversions")
    val spilloverConversions: java.math.BigDecimal,

    @Json(name = "spilloverRevenueCents")
    val spilloverRevenueCents: java.math.BigDecimal,

    @Json(name = "returnBps")
    val returnBps: java.math.BigDecimal,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "autoPausedAt")
    val autoPausedAt: kotlin.String? = null,

    @Json(name = "autoPausedReason")
    val autoPausedReason: kotlin.String? = null

)

