/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetBuyerPreferenceResponseBrands
import net.crossly.models.GetBuyerPreferenceResponsePriceBand
import net.crossly.models.GetBuyerPreferenceResponseRetailers

import com.squareup.moshi.Json

/**
 * 
 *
 * @param retailers Retailers they shop, most-seen first.
 * @param brands What they look at, by catalog brand where we could resolve one.
 * @param observations 
 * @param priceBand 
 * @param matchRate How much of what they want we can actually supply.
 */

data class GetBuyerPreferenceResponse (

    /* Retailers they shop, most-seen first. */
    @Json(name = "retailers")
    val retailers: kotlin.collections.List<GetBuyerPreferenceResponseRetailers>,

    /* What they look at, by catalog brand where we could resolve one. */
    @Json(name = "brands")
    val brands: kotlin.collections.List<GetBuyerPreferenceResponseBrands>,

    @Json(name = "observations")
    val observations: java.math.BigDecimal,

    @Json(name = "priceBand")
    val priceBand: GetBuyerPreferenceResponsePriceBand? = null,

    /* How much of what they want we can actually supply. */
    @Json(name = "matchRate")
    val matchRate: java.math.BigDecimal? = null

)

