/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * The band they actually shop in, from retail prices they were looking at.
 *
 * @param p25Cents 
 * @param medianCents 
 * @param p75Cents 
 */

data class GetBuyerPreferenceResponsePriceBand (

    @Json(name = "p25Cents")
    val p25Cents: java.math.BigDecimal,

    @Json(name = "medianCents")
    val medianCents: java.math.BigDecimal,

    @Json(name = "p75Cents")
    val p75Cents: java.math.BigDecimal

)

