/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetCatalogLookupResponseCatalog

import com.squareup.moshi.Json

/**
 * 
 *
 * @param kind 
 * @param priceCents 
 * @param currency 
 * @param url 
 * @param condition 
 * @param title 
 * @param imageUrl 
 * @param listingSlug Null on an order-book ask, which is a price rather than a purchasable listing.
 * @param available 
 * @param catalog 
 */

data class GetCatalogLookupResponseOffers (

    @Json(name = "kind")
    val kind: GetCatalogLookupResponseOffers.Kind,

    @Json(name = "priceCents")
    val priceCents: java.math.BigDecimal,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "condition")
    val condition: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,

    /* Null on an order-book ask, which is a price rather than a purchasable listing. */
    @Json(name = "listingSlug")
    val listingSlug: kotlin.String? = null,

    @Json(name = "available")
    val available: java.math.BigDecimal? = null,

    @Json(name = "catalog")
    val catalog: GetCatalogLookupResponseCatalog? = null

) {

    /**
     * 
     *
     * Values: listing,ask
     */
    enum class Kind(val value: kotlin.String) {
        @Json(name = "listing") listing("listing"),
        @Json(name = "ask") ask("ask");
    }
}

