/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetCustomerResponseContact
import net.crossly.models.GetCustomerResponseOrders

import com.squareup.moshi.Json

/**
 * 
 *
 * @param normalizedHandle 
 * @param platforms 
 * @param totalOrders 
 * @param totalSpent 
 * @param orders 
 * @param contact 
 */

data class GetCustomerResponse (

    @Json(name = "normalizedHandle")
    val normalizedHandle: kotlin.String,

    @Json(name = "platforms")
    val platforms: kotlin.collections.List<kotlin.String>,

    @Json(name = "totalOrders")
    val totalOrders: java.math.BigDecimal,

    @Json(name = "totalSpent")
    val totalSpent: java.math.BigDecimal,

    @Json(name = "orders")
    val orders: kotlin.collections.List<GetCustomerResponseOrders>,

    @Json(name = "contact")
    val contact: GetCustomerResponseContact

)

