/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param grantedBaseUnits 
 * @param earnedBaseUnits 
 * @param stakedBaseUnits 
 * @param earnedAvailableBaseUnits 
 * @param connectedAvailableBaseUnits 
 * @param totalSpendableBaseUnits 
 */

data class GetCbxSubjectBalanceBySubjectIdResponse (

    @Json(name = "grantedBaseUnits")
    val grantedBaseUnits: kotlin.String,

    @Json(name = "earnedBaseUnits")
    val earnedBaseUnits: kotlin.String,

    @Json(name = "stakedBaseUnits")
    val stakedBaseUnits: kotlin.String,

    @Json(name = "earnedAvailableBaseUnits")
    val earnedAvailableBaseUnits: kotlin.String,

    @Json(name = "connectedAvailableBaseUnits")
    val connectedAvailableBaseUnits: kotlin.String,

    @Json(name = "totalSpendableBaseUnits")
    val totalSpendableBaseUnits: kotlin.String

)

