/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param platform 
 * @param listingsThisMonth 
 * @param costSoFarUsd 
 * @param perListingFeeUsd 
 * @param periodStart 
 */

data class GetPlatformLimitResponseEtsy (

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "listingsThisMonth")
    val listingsThisMonth: java.math.BigDecimal,

    @Json(name = "costSoFarUsd")
    val costSoFarUsd: java.math.BigDecimal,

    @Json(name = "perListingFeeUsd")
    val perListingFeeUsd: java.math.BigDecimal,

    @Json(name = "periodStart")
    val periodStart: kotlin.String

)

