/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetSpatialPublicResponseProfile
import net.crossly.models.GetSpatialPublicResponseSolved
import net.crossly.models.GetSpatialSceneResponseBreakdowns
import net.crossly.models.GetSpatialSceneResponseItems
import net.crossly.models.GetSpatialSceneResponseScene
import net.crossly.models.GetSpatialSceneResponseStats

import com.squareup.moshi.Json

/**
 * 
 *
 * @param breakdowns Facets that would actually split this collection, most-dividing first.  Drives the breakdown picker — see availableBreakdowns.
 * @param scene 
 * @param profile 
 * @param solved 
 * @param items 
 * @param stats 
 */

data class GetSpatialSceneResponse (

    /* Facets that would actually split this collection, most-dividing first.  Drives the breakdown picker — see availableBreakdowns. */
    @Json(name = "breakdowns")
    val breakdowns: kotlin.collections.List<GetSpatialSceneResponseBreakdowns>,

    @Json(name = "scene")
    val scene: GetSpatialSceneResponseScene,

    @Json(name = "profile")
    val profile: GetSpatialPublicResponseProfile,

    @Json(name = "solved")
    val solved: GetSpatialPublicResponseSolved,

    @Json(name = "items")
    val items: kotlin.collections.List<GetSpatialSceneResponseItems>,

    @Json(name = "stats")
    val stats: GetSpatialSceneResponseStats

)

