/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.GetSpatialPublicResponseItems
import net.crossly.models.GetSpatialPublicResponseProfile
import net.crossly.models.GetSpatialPublicResponseScene
import net.crossly.models.GetSpatialPublicResponseSolved
import net.crossly.models.GetSpatialPublicResponseStats

import com.squareup.moshi.Json

/**
 * 
 *
 * @param scene 
 * @param profile 
 * @param solved 
 * @param items Enough to draw an object and label it. No cost, no location, no status.
 * @param stats 
 */

data class GetSpatialPublicResponse (

    @Json(name = "scene")
    val scene: GetSpatialPublicResponseScene,

    @Json(name = "profile")
    val profile: GetSpatialPublicResponseProfile,

    @Json(name = "solved")
    val solved: GetSpatialPublicResponseSolved,

    /* Enough to draw an object and label it. No cost, no location, no status. */
    @Json(name = "items")
    val items: kotlin.collections.List<GetSpatialPublicResponseItems>,

    @Json(name = "stats")
    val stats: GetSpatialPublicResponseStats

)

