/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * Totals the UI shows without recomputing over the payload.
 *
 * @param itemCount 
 * @param capitalCents 
 * @param staleCount 
 * @param unplaced 
 */

data class GetSpatialSceneResponseStats (

    @Json(name = "itemCount")
    val itemCount: java.math.BigDecimal,

    @Json(name = "capitalCents")
    val capitalCents: java.math.BigDecimal,

    @Json(name = "staleCount")
    val staleCount: java.math.BigDecimal,

    @Json(name = "unplaced")
    val unplaced: java.math.BigDecimal

)

