/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name 
 * @param required 
 * @param dataType 'STRING' | 'NUMBER' | 'DATE' — eBay's dataType per aspect.
 * @param hasEnumValues True when the aspect is selection-only (no free-text).
 * @param cardinality Cardinality — SINGLE_VALUE / MULTIPLE_VALUES.
 * @param enumValues 
 * @param maxLength Helpful for client validation — max length when supplied.
 */

data class GetTaxonomyCategoryAspectResponseAspects (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "required")
    val required: kotlin.Boolean,

    /* 'STRING' | 'NUMBER' | 'DATE' — eBay's dataType per aspect. */
    @Json(name = "dataType")
    val dataType: kotlin.String,

    /* True when the aspect is selection-only (no free-text). */
    @Json(name = "hasEnumValues")
    val hasEnumValues: kotlin.Boolean,

    /* Cardinality — SINGLE_VALUE / MULTIPLE_VALUES. */
    @Json(name = "cardinality")
    val cardinality: kotlin.String,

    @Json(name = "enumValues")
    val enumValues: kotlin.collections.List<kotlin.String>? = null,

    /* Helpful for client validation — max length when supplied. */
    @Json(name = "maxLength")
    val maxLength: java.math.BigDecimal? = null

)

