/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.ListVariationGroupsItemMembers
import net.crossly.models.ListVariationGroupsItemRollup

import com.squareup.moshi.Json

/**
 * 
 *
 * @param members 
 * @param rollup 
 * @param id 
 * @param title 
 */

data class GetVariationGroupResponse (

    @Json(name = "members")
    val members: kotlin.collections.List<ListVariationGroupsItemMembers>,

    @Json(name = "rollup")
    val rollup: ListVariationGroupsItemRollup,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String? = null

)

