/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param at 
 * @param kind 
 * @param source 
 * @param quantity 
 * @param itemId 
 * @param unitId 
 * @param title 
 * @param fromNodeId 
 * @param toNodeId 
 * @param fromCode 
 * @param toCode 
 * @param actorId NULL when nothing human did it, OR when attribution is redacted for this caller. `actorsRedacted` on the payload distinguishes the two.
 */

data class ListSpatialSceneMovementsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "at")
    val at: kotlin.String,

    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    @Json(name = "itemId")
    val itemId: kotlin.String,

    @Json(name = "unitId")
    val unitId: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "fromNodeId")
    val fromNodeId: kotlin.String? = null,

    @Json(name = "toNodeId")
    val toNodeId: kotlin.String? = null,

    @Json(name = "fromCode")
    val fromCode: kotlin.String? = null,

    @Json(name = "toCode")
    val toCode: kotlin.String? = null,

    /* NULL when nothing human did it, OR when attribution is redacted for this caller. `actorsRedacted` on the payload distinguishes the two. */
    @Json(name = "actorId")
    val actorId: kotlin.String? = null

)

