/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param status 
 * @param storeName 
 * @param storeHost 
 * @param activatedAt 
 * @param orderCents 
 * @param cashbackCents What WE will pay. Never the commission — that is our revenue and is not the shopper's business.
 * @param confirmedAt 
 * @param paidAt 
 * @param expiredAt 
 * @param rejectedReason 
 */

data class ListBuyerCashbackItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "storeName")
    val storeName: kotlin.String,

    @Json(name = "storeHost")
    val storeHost: kotlin.String,

    @Json(name = "activatedAt")
    val activatedAt: java.time.OffsetDateTime,

    @Json(name = "orderCents")
    val orderCents: java.math.BigDecimal? = null,

    /* What WE will pay. Never the commission — that is our revenue and is not the shopper's business. */
    @Json(name = "cashbackCents")
    val cashbackCents: java.math.BigDecimal? = null,

    @Json(name = "confirmedAt")
    val confirmedAt: java.time.OffsetDateTime? = null,

    @Json(name = "paidAt")
    val paidAt: java.time.OffsetDateTime? = null,

    @Json(name = "expiredAt")
    val expiredAt: java.time.OffsetDateTime? = null,

    @Json(name = "rejectedReason")
    val rejectedReason: kotlin.String? = null

)

