/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param platformListingId 
 * @param addedAt 
 * @param slug 
 * @param title 
 */

data class ListBuyerWishlistItemsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "platformListingId")
    val platformListingId: kotlin.String,

    @Json(name = "addedAt")
    val addedAt: java.time.OffsetDateTime,

    @Json(name = "slug")
    val slug: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null

)

