/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.ListSalesItemDocuments

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param platform 
 * @param detectedBy 
 * @param detectedAt 
 * @param cancelledAt 
 * @param orderId 
 * @param listingId 
 * @param inventoryItemId 
 * @param platformListingId 
 * @param platformOrderId 
 * @param costOfGoods 
 * @param deletedAt 
 * @param salePrice 
 * @param platformFee 
 * @param shippingCost 
 * @param netProfit 
 * @param taxCollected 
 * @param shippingCharged 
 * @param feeSource 
 * @param documents 
 * @param refundedAmount 
 */

data class ListSalesItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "userId")
    val userId: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "detectedBy")
    val detectedBy: kotlin.String,

    @Json(name = "detectedAt")
    val detectedAt: java.time.OffsetDateTime,

    @Json(name = "cancelledAt")
    val cancelledAt: java.time.OffsetDateTime? = null,

    @Json(name = "orderId")
    val orderId: kotlin.String? = null,

    @Json(name = "listingId")
    val listingId: kotlin.String? = null,

    @Json(name = "inventoryItemId")
    val inventoryItemId: kotlin.String? = null,

    @Json(name = "platformListingId")
    val platformListingId: kotlin.String? = null,

    @Json(name = "platformOrderId")
    val platformOrderId: kotlin.String? = null,

    @Json(name = "costOfGoods")
    val costOfGoods: kotlin.String? = null,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime? = null,

    @Json(name = "salePrice")
    val salePrice: kotlin.String? = null,

    @Json(name = "platformFee")
    val platformFee: kotlin.String? = null,

    @Json(name = "shippingCost")
    val shippingCost: kotlin.String? = null,

    @Json(name = "netProfit")
    val netProfit: kotlin.String? = null,

    @Json(name = "taxCollected")
    val taxCollected: kotlin.String? = null,

    @Json(name = "shippingCharged")
    val shippingCharged: kotlin.String? = null,

    @Json(name = "feeSource")
    val feeSource: kotlin.String? = null,

    @Json(name = "documents")
    val documents: kotlin.collections.List<ListSalesItemDocuments>? = null,

    @Json(name = "refundedAmount")
    val refundedAmount: kotlin.String? = null

)

