/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param url 
 * @param events 
 * @param enabled 
 * @param consecutiveFailures 
 * @param createdAt 
 * @param description 
 * @param lastDeliveryAt 
 * @param lastErrorAt 
 * @param lastError 
 */

data class ListWebhooksItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "consecutiveFailures")
    val consecutiveFailures: java.math.BigDecimal,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "lastDeliveryAt")
    val lastDeliveryAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastErrorAt")
    val lastErrorAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastError")
    val lastError: kotlin.String? = null

)

