/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param namespace 
 * @param `value` 
 * @param source 
 * @param recordedAt 
 * @param strength 
 */

data class ListInventoryUnitsItemIdentifiers (

    @Json(name = "namespace")
    val namespace: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "recordedAt")
    val recordedAt: java.time.OffsetDateTime,

    @Json(name = "strength")
    val strength: ListInventoryUnitsItemIdentifiers.Strength

) {

    /**
     * 
     *
     * Values: strong,good,weak
     */
    enum class Strength(val value: kotlin.String) {
        @Json(name = "strong") strong("strong"),
        @Json(name = "good") good("good"),
        @Json(name = "weak") weak("weak");
    }
}

