/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param grantId 
 * @param scopes 
 * @param connectedAt 
 * @param appId 
 * @param appName 
 * @param developerEmail 
 * @param lastUsedAt 
 * @param appDescription 
 * @param homepageUrl 
 * @param developerName 
 */

data class ListConnectedAppsItem (

    @Json(name = "grantId")
    val grantId: kotlin.String,

    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @Json(name = "connectedAt")
    val connectedAt: java.time.OffsetDateTime,

    @Json(name = "appId")
    val appId: kotlin.String,

    @Json(name = "appName")
    val appName: kotlin.String,

    @Json(name = "developerEmail")
    val developerEmail: kotlin.String,

    @Json(name = "lastUsedAt")
    val lastUsedAt: java.time.OffsetDateTime? = null,

    @Json(name = "appDescription")
    val appDescription: kotlin.String? = null,

    @Json(name = "homepageUrl")
    val homepageUrl: kotlin.String? = null,

    @Json(name = "developerName")
    val developerName: kotlin.String? = null

)

