/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param targetKind 
 * @param boostedRateBps 
 * @param budgetCents 
 * @param spentCents 
 * @param remainingCents 
 * @param startsAt 
 * @param endsAt 
 * @param status 
 * @param targetValue 
 */

data class ListCbxBoostsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "targetKind")
    val targetKind: kotlin.String,

    @Json(name = "boostedRateBps")
    val boostedRateBps: java.math.BigDecimal,

    @Json(name = "budgetCents")
    val budgetCents: java.math.BigDecimal,

    @Json(name = "spentCents")
    val spentCents: java.math.BigDecimal,

    @Json(name = "remainingCents")
    val remainingCents: java.math.BigDecimal,

    @Json(name = "startsAt")
    val startsAt: kotlin.String,

    @Json(name = "endsAt")
    val endsAt: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "targetValue")
    val targetValue: kotlin.String? = null

)

