/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param listedAfter 
 * @param listedBefore 
 * @param minPrice 
 * @param maxPrice 
 * @param conditionIncludes 
 * @param maxImport 
 */

data class ListImportsItemFilters (

    @Json(name = "listedAfter")
    val listedAfter: kotlin.String? = null,

    @Json(name = "listedBefore")
    val listedBefore: kotlin.String? = null,

    @Json(name = "minPrice")
    val minPrice: java.math.BigDecimal? = null,

    @Json(name = "maxPrice")
    val maxPrice: java.math.BigDecimal? = null,

    @Json(name = "conditionIncludes")
    val conditionIncludes: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "maxImport")
    val maxImport: java.math.BigDecimal? = null

)

