/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param active 
 * @param matchCount 
 * @param createdAt 
 * @param id 
 * @param name 
 * @param kind 
 * @param delivery 
 * @param pausedReason 
 * @param lastCheckedAt 
 * @param lastMatchAt 
 * @param webhookSecret 
 * @param webhookUrl 
 */

data class UpdateBuyerMonitorResponse (

    @Json(name = "active")
    val active: kotlin.Boolean,

    @Json(name = "matchCount")
    val matchCount: java.math.BigDecimal,

    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "kind")
    val kind: UpdateBuyerMonitorResponse.Kind,

    @Json(name = "delivery")
    val delivery: UpdateBuyerMonitorResponse.Delivery,

    @Json(name = "pausedReason")
    val pausedReason: kotlin.String? = null,

    @Json(name = "lastCheckedAt")
    val lastCheckedAt: kotlin.String? = null,

    @Json(name = "lastMatchAt")
    val lastMatchAt: kotlin.String? = null,

    @Json(name = "webhookSecret")
    val webhookSecret: kotlin.String? = null,

    @Json(name = "webhookUrl")
    val webhookUrl: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: newListing,priceDrop,backInStock
     */
    enum class Kind(val value: kotlin.String) {
        @Json(name = "new_listing") newListing("new_listing"),
        @Json(name = "price_drop") priceDrop("price_drop"),
        @Json(name = "back_in_stock") backInStock("back_in_stock");
    }
    /**
     * 
     *
     * Values: webhook,poll
     */
    enum class Delivery(val value: kotlin.String) {
        @Json(name = "webhook") webhook("webhook"),
        @Json(name = "poll") poll("poll");
    }
}

