/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.models

import net.crossly.models.Pagination

import com.squareup.moshi.Json

/**
 * The canonical collection envelope. The array is ALWAYS under `data`, never under the noun — so one accessor works for every list endpoint.
 *
 * @param `data` The rows.
 * @param pagination 
 * @param meta Endpoint-specific extras that are NOT pagination — e.g. `pendingCents`, `basis`. Omitted when empty.
 */

data class V1List (

    /* The rows. */
    @Json(name = "data")
    val `data`: kotlin.collections.List<kotlin.Any>,

    @Json(name = "pagination")
    val pagination: Pagination? = null,

    /* Endpoint-specific extras that are NOT pagination — e.g. `pendingCents`, `basis`. Omitted when empty. */
    @Json(name = "meta")
    val meta: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

