/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.apis

import java.io.IOException

import net.crossly.buyer.models.CreateBuyerActivityResponse
import net.crossly.buyer.models.CreateBuyerCartItemResponse
import net.crossly.buyer.models.CreateBuyerCartQuoteResponse
import net.crossly.buyer.models.CreateBuyerOfferResponse
import net.crossly.buyer.models.CreateBuyerWishlistItemResponse
import net.crossly.buyer.models.CreateBuyerWishlistResponse
import net.crossly.buyer.models.Error
import net.crossly.buyer.models.GetBuyerPreferenceResponse
import net.crossly.buyer.models.GetBuyerProfileResponse
import net.crossly.buyer.models.InlineObject
import net.crossly.buyer.models.InlineObject1
import net.crossly.buyer.models.InlineObject2
import net.crossly.buyer.models.InlineObject3
import net.crossly.buyer.models.InlineObject4
import net.crossly.buyer.models.ListBuyerActivityItem
import net.crossly.buyer.models.ListBuyerCartItem
import net.crossly.buyer.models.ListBuyerCashbackItem
import net.crossly.buyer.models.ListBuyerOrdersItem
import net.crossly.buyer.models.ListBuyerWishlistItemsItem
import net.crossly.buyer.models.ListBuyerWishlistsItem
import net.crossly.buyer.models.V1List

import com.squareup.moshi.Json

import net.crossly.buyer.infrastructure.ApiClient
import net.crossly.buyer.infrastructure.ApiResponse
import net.crossly.buyer.infrastructure.ClientException
import net.crossly.buyer.infrastructure.ClientError
import net.crossly.buyer.infrastructure.ServerException
import net.crossly.buyer.infrastructure.ServerError
import net.crossly.buyer.infrastructure.MultiValueMap
import net.crossly.buyer.infrastructure.RequestConfig
import net.crossly.buyer.infrastructure.RequestMethod
import net.crossly.buyer.infrastructure.ResponseType
import net.crossly.buyer.infrastructure.Success
import net.crossly.buyer.infrastructure.toMultiValue

class BuyerApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://crossly.net/api")
        }
    }

    /**
    * Report an item your user is looking at, and get our answer.
    * Records the look and returns whether Crossly has the item and at what price. Send an identifier and a store DOMAIN — a full URL is refused. Nothing about the page itself is stored.
    * @param inlineObject4  
    * @return CreateBuyerActivityResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerActivity(inlineObject4: InlineObject4) : CreateBuyerActivityResponse {
        val localVarResponse = createBuyerActivityWithHttpInfo(inlineObject4 = inlineObject4)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerActivityResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Report an item your user is looking at, and get our answer.
    * Records the look and returns whether Crossly has the item and at what price. Send an identifier and a store DOMAIN — a full URL is refused. Nothing about the page itself is stored.
    * @param inlineObject4  
    * @return ApiResponse<CreateBuyerActivityResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerActivityWithHttpInfo(inlineObject4: InlineObject4) : ApiResponse<CreateBuyerActivityResponse?> {
        val localVariableConfig = createBuyerActivityRequestConfig(inlineObject4 = inlineObject4)

        return request<InlineObject4, CreateBuyerActivityResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerActivity
    *
    * @param inlineObject4  
    * @return RequestConfig
    */
    fun createBuyerActivityRequestConfig(inlineObject4: InlineObject4) : RequestConfig<InlineObject4> {
        val localVariableBody = inlineObject4
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/activity",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Add a listing to your cart.
    * 
    * @param inlineObject2  
    * @return CreateBuyerCartItemResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerCartItem(inlineObject2: InlineObject2) : CreateBuyerCartItemResponse {
        val localVarResponse = createBuyerCartItemWithHttpInfo(inlineObject2 = inlineObject2)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerCartItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Add a listing to your cart.
    * 
    * @param inlineObject2  
    * @return ApiResponse<CreateBuyerCartItemResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerCartItemWithHttpInfo(inlineObject2: InlineObject2) : ApiResponse<CreateBuyerCartItemResponse?> {
        val localVariableConfig = createBuyerCartItemRequestConfig(inlineObject2 = inlineObject2)

        return request<InlineObject2, CreateBuyerCartItemResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerCartItem
    *
    * @param inlineObject2  
    * @return RequestConfig
    */
    fun createBuyerCartItemRequestConfig(inlineObject2: InlineObject2) : RequestConfig<InlineObject2> {
        val localVariableBody = inlineObject2
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/cart/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Price the cart, delivered — item, shipping, tax, total.
    * Runs the real checkout cascade and returns the totals instead of charging. Nothing is purchased. &#x60;taxComplete: false&#x60; means there is no saved delivery address, so the total is a floor rather than a final figure.
    * @return CreateBuyerCartQuoteResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerCartQuote() : CreateBuyerCartQuoteResponse {
        val localVarResponse = createBuyerCartQuoteWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerCartQuoteResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Price the cart, delivered — item, shipping, tax, total.
    * Runs the real checkout cascade and returns the totals instead of charging. Nothing is purchased. &#x60;taxComplete: false&#x60; means there is no saved delivery address, so the total is a floor rather than a final figure.
    * @return ApiResponse<CreateBuyerCartQuoteResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerCartQuoteWithHttpInfo() : ApiResponse<CreateBuyerCartQuoteResponse?> {
        val localVariableConfig = createBuyerCartQuoteRequestConfig()

        return request<Unit, CreateBuyerCartQuoteResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerCartQuote
    *
    * @return RequestConfig
    */
    fun createBuyerCartQuoteRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/cart/quote",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Offer a price on a listing.
    * Sends an offer to the seller. Spends nothing — a seller accepting still leaves you to complete checkout. Offers at or above the asking price are refused; buy it instead.
    * @param inlineObject3  
    * @return CreateBuyerOfferResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerOffer(inlineObject3: InlineObject3) : CreateBuyerOfferResponse {
        val localVarResponse = createBuyerOfferWithHttpInfo(inlineObject3 = inlineObject3)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerOfferResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Offer a price on a listing.
    * Sends an offer to the seller. Spends nothing — a seller accepting still leaves you to complete checkout. Offers at or above the asking price are refused; buy it instead.
    * @param inlineObject3  
    * @return ApiResponse<CreateBuyerOfferResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerOfferWithHttpInfo(inlineObject3: InlineObject3) : ApiResponse<CreateBuyerOfferResponse?> {
        val localVariableConfig = createBuyerOfferRequestConfig(inlineObject3 = inlineObject3)

        return request<InlineObject3, CreateBuyerOfferResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerOffer
    *
    * @param inlineObject3  
    * @return RequestConfig
    */
    fun createBuyerOfferRequestConfig(inlineObject3: InlineObject3) : RequestConfig<InlineObject3> {
        val localVariableBody = inlineObject3
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/offers",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Create a wishlist.
    * 
    * @param inlineObject  
    * @return CreateBuyerWishlistResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerWishlist(inlineObject: InlineObject) : CreateBuyerWishlistResponse {
        val localVarResponse = createBuyerWishlistWithHttpInfo(inlineObject = inlineObject)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerWishlistResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Create a wishlist.
    * 
    * @param inlineObject  
    * @return ApiResponse<CreateBuyerWishlistResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerWishlistWithHttpInfo(inlineObject: InlineObject) : ApiResponse<CreateBuyerWishlistResponse?> {
        val localVariableConfig = createBuyerWishlistRequestConfig(inlineObject = inlineObject)

        return request<InlineObject, CreateBuyerWishlistResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerWishlist
    *
    * @param inlineObject  
    * @return RequestConfig
    */
    fun createBuyerWishlistRequestConfig(inlineObject: InlineObject) : RequestConfig<InlineObject> {
        val localVariableBody = inlineObject
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/wishlists",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Add a listing to a wishlist.
    * 
    * @param id  
    * @param inlineObject1  
    * @return CreateBuyerWishlistItemResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createBuyerWishlistItem(id: java.util.UUID, inlineObject1: InlineObject1) : CreateBuyerWishlistItemResponse {
        val localVarResponse = createBuyerWishlistItemWithHttpInfo(id = id, inlineObject1 = inlineObject1)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreateBuyerWishlistItemResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Add a listing to a wishlist.
    * 
    * @param id  
    * @param inlineObject1  
    * @return ApiResponse<CreateBuyerWishlistItemResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createBuyerWishlistItemWithHttpInfo(id: java.util.UUID, inlineObject1: InlineObject1) : ApiResponse<CreateBuyerWishlistItemResponse?> {
        val localVariableConfig = createBuyerWishlistItemRequestConfig(id = id, inlineObject1 = inlineObject1)

        return request<InlineObject1, CreateBuyerWishlistItemResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation createBuyerWishlistItem
    *
    * @param id  
    * @param inlineObject1  
    * @return RequestConfig
    */
    fun createBuyerWishlistItemRequestConfig(id: java.util.UUID, inlineObject1: InlineObject1) : RequestConfig<InlineObject1> {
        val localVariableBody = inlineObject1
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/buyer/wishlists/{id}/items".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Remove a line from your cart.
    * 
    * @param id  
    * @return void
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteBuyerCartItem(id: java.util.UUID) : Unit {
        val localVarResponse = deleteBuyerCartItemWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Remove a line from your cart.
    * 
    * @param id  
    * @return ApiResponse<Unit?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteBuyerCartItemWithHttpInfo(id: java.util.UUID) : ApiResponse<Unit?> {
        val localVariableConfig = deleteBuyerCartItemRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation deleteBuyerCartItem
    *
    * @param id  
    * @return RequestConfig
    */
    fun deleteBuyerCartItemRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/buyer/cart/items/{id}".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * The shopping profile derived from that activity.
    * Derived, never declared — there is no preferences form anywhere. &#x60;matchRate&#x60; is the share of this person&#39;s searches Crossly could answer; a low number is an inventory problem, not a personalisation one, which is why it is here.
    * @return GetBuyerPreferenceResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getBuyerPreference() : GetBuyerPreferenceResponse {
        val localVarResponse = getBuyerPreferenceWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetBuyerPreferenceResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * The shopping profile derived from that activity.
    * Derived, never declared — there is no preferences form anywhere. &#x60;matchRate&#x60; is the share of this person&#39;s searches Crossly could answer; a low number is an inventory problem, not a personalisation one, which is why it is here.
    * @return ApiResponse<GetBuyerPreferenceResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getBuyerPreferenceWithHttpInfo() : ApiResponse<GetBuyerPreferenceResponse?> {
        val localVariableConfig = getBuyerPreferenceRequestConfig()

        return request<Unit, GetBuyerPreferenceResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation getBuyerPreference
    *
    * @return RequestConfig
    */
    fun getBuyerPreferenceRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/preferences",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Your Crossly shopping profile — name, email, saved address, Bucks balance.
    * 
    * @return GetBuyerProfileResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getBuyerProfile() : GetBuyerProfileResponse {
        val localVarResponse = getBuyerProfileWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetBuyerProfileResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Your Crossly shopping profile — name, email, saved address, Bucks balance.
    * 
    * @return ApiResponse<GetBuyerProfileResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getBuyerProfileWithHttpInfo() : ApiResponse<GetBuyerProfileResponse?> {
        val localVariableConfig = getBuyerProfileRequestConfig()

        return request<Unit, GetBuyerProfileResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation getBuyerProfile
    *
    * @return RequestConfig
    */
    fun getBuyerProfileRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/profile",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * What this buyer has compared lately.
    * Newest first, and only as far back as the retention window — the link between a person and a comparison is dropped after 180 days, so this thins out rather than growing forever.
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerActivity() : V1List {
        val localVarResponse = listBuyerActivityWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * What this buyer has compared lately.
    * Newest first, and only as far back as the retention window — the link between a person and a comparison is dropped after 180 days, so this thins out rather than growing forever.
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerActivityWithHttpInfo() : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerActivityRequestConfig()

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerActivity
    *
    * @return RequestConfig
    */
    fun listBuyerActivityRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/activity",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * What is in your Crossly cart.
    * Line items with the price captured when each was added. This is NOT a quote — shipping, tax and any discounts are computed at checkout against a delivery address, and the sum of these lines is not what you will be charged.
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerCart() : V1List {
        val localVarResponse = listBuyerCartWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * What is in your Crossly cart.
    * Line items with the price captured when each was added. This is NOT a quote — shipping, tax and any discounts are computed at checkout against a delivery address, and the sum of these lines is not what you will be charged.
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerCartWithHttpInfo() : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerCartRequestConfig()

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerCart
    *
    * @return RequestConfig
    */
    fun listBuyerCartRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/cart",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter status
     */
     enum class Status_listBuyerCashback(val value: kotlin.String) {
         @Json(name = "pending") pending("pending"),
         @Json(name = "confirmed") confirmed("confirmed"),
         @Json(name = "rejected") rejected("rejected"),
         @Json(name = "paid") paid("paid"),
         @Json(name = "expired") expired("expired"),
         ;
     }

    /**
    * Your Scout cashback — pending, confirmed, paid.
    * Newest first. &#x60;pending&#x60; means an order was reported and the retailer&#39;s return window has not closed; nothing is paid until it does. &#x60;expired&#x60; means a click was never reported as converting, which is the ordinary outcome for most clicks.
    * @param status  (optional)
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerCashback(status: Status_listBuyerCashback?, page: kotlin.Int?, limit: kotlin.Int?) : V1List {
        val localVarResponse = listBuyerCashbackWithHttpInfo(status = status, page = page, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Your Scout cashback — pending, confirmed, paid.
    * Newest first. &#x60;pending&#x60; means an order was reported and the retailer&#39;s return window has not closed; nothing is paid until it does. &#x60;expired&#x60; means a click was never reported as converting, which is the ordinary outcome for most clicks.
    * @param status  (optional)
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerCashbackWithHttpInfo(status: Status_listBuyerCashback?, page: kotlin.Int?, limit: kotlin.Int?) : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerCashbackRequestConfig(status = status, page = page, limit = limit)

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerCashback
    *
    * @param status  (optional)
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return RequestConfig
    */
    fun listBuyerCashbackRequestConfig(status: Status_listBuyerCashback?, page: kotlin.Int?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/cashback",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * What you have bought on Crossly, newest first.
    * 
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerOrders(page: kotlin.Int?, limit: kotlin.Int?) : V1List {
        val localVarResponse = listBuyerOrdersWithHttpInfo(page = page, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * What you have bought on Crossly, newest first.
    * 
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerOrdersWithHttpInfo(page: kotlin.Int?, limit: kotlin.Int?) : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerOrdersRequestConfig(page = page, limit = limit)

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerOrders
    *
    * @param page  (optional, default to 1)
    * @param limit  (optional, default to 25)
    * @return RequestConfig
    */
    fun listBuyerOrdersRequestConfig(page: kotlin.Int?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/orders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * What is on one wishlist.
    * 
    * @param id  
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerWishlistItems(id: java.util.UUID) : V1List {
        val localVarResponse = listBuyerWishlistItemsWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * What is on one wishlist.
    * 
    * @param id  
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerWishlistItemsWithHttpInfo(id: java.util.UUID) : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerWishlistItemsRequestConfig(id = id)

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerWishlistItems
    *
    * @param id  
    * @return RequestConfig
    */
    fun listBuyerWishlistItemsRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/wishlists/{id}/items".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Your wishlists.
    * 
    * @return V1List
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listBuyerWishlists() : V1List {
        val localVarResponse = listBuyerWishlistsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as V1List
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Your wishlists.
    * 
    * @return ApiResponse<V1List?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listBuyerWishlistsWithHttpInfo() : ApiResponse<V1List?> {
        val localVariableConfig = listBuyerWishlistsRequestConfig()

        return request<Unit, V1List>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation listBuyerWishlists
    *
    * @return RequestConfig
    */
    fun listBuyerWishlistsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/buyer/wishlists",
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
