/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param updated 
 * @param skipped Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch.
 */

data class CreateOrderBulkMarkShippedResponse (

    @Json(name = "updated")
    val updated: java.math.BigDecimal,

    /* Cancelled/refunded orders in the request that were left untouched — reported so a caller can't mistake a partial success for \"all done\" and miss that a closed order was in the batch. */
    @Json(name = "skipped")
    val skipped: java.math.BigDecimal

)

