/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param status 
 * @param txSig 
 * @param reason 
 */

data class CreateCbxClaimSendResponse (

    @Json(name = "status")
    val status: CreateCbxClaimSendResponse.Status,

    @Json(name = "txSig")
    val txSig: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: confirmed,failed,unconfirmed
     */
    enum class Status(val value: kotlin.String) {
        @Json(name = "confirmed") confirmed("confirmed"),
        @Json(name = "failed") failed("failed"),
        @Json(name = "unconfirmed") unconfirmed("unconfirmed");
    }
}

