/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.CreateCbxRevenueSweepResponseBreakdown

import com.squareup.moshi.Json

/**
 * 
 *
 * @param swept 
 * @param baseUnits 
 * @param txSig 
 * @param reason 
 * @param breakdown 
 */

data class CreateCbxRevenueSweepResponse (

    @Json(name = "swept")
    val swept: kotlin.Boolean,

    @Json(name = "baseUnits")
    val baseUnits: kotlin.String,

    @Json(name = "txSig")
    val txSig: kotlin.String? = null,

    @Json(name = "reason")
    val reason: kotlin.String? = null,

    @Json(name = "breakdown")
    val breakdown: CreateCbxRevenueSweepResponseBreakdown? = null

)

