/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param createdAt 
 * @param userId 
 * @param brand 
 * @param condition 
 * @param categoryMain 
 * @param platform 
 * @param minPrice 
 * @param maxPrice 
 * @param lastMatchedAt 
 * @param lastScrapedAt 
 */

data class CreateCompWatchlistResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "userId")
    val userId: kotlin.String,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "condition")
    val condition: kotlin.String? = null,

    @Json(name = "categoryMain")
    val categoryMain: kotlin.String? = null,

    @Json(name = "platform")
    val platform: kotlin.String? = null,

    @Json(name = "minPrice")
    val minPrice: kotlin.String? = null,

    @Json(name = "maxPrice")
    val maxPrice: kotlin.String? = null,

    @Json(name = "lastMatchedAt")
    val lastMatchedAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastScrapedAt")
    val lastScrapedAt: java.time.OffsetDateTime? = null

)

