/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param line 1-based, and counting the header — so it matches what the seller sees  in their spreadsheet. Off-by-one here makes every error unfindable.
 * @param message 
 */

data class CreateInventoryCsvImportResponseProblems (

    /* 1-based, and counting the header — so it matches what the seller sees  in their spreadsheet. Off-by-one here makes every error unfindable. */
    @Json(name = "line")
    val line: java.math.BigDecimal,

    @Json(name = "message")
    val message: kotlin.String

)

