/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ns 
 * @param `value` 
 */

data class CreateBuyerIdentifyResponseIdentifier (

    @Json(name = "ns")
    val ns: CreateBuyerIdentifyResponseIdentifier.Ns,

    @Json(name = "value")
    val `value`: kotlin.String

) {

    /**
     * 
     *
     * Values: styleCode,gtin,legoSet,tcgplayer,discogs,asin
     */
    enum class Ns(val value: kotlin.String) {
        @Json(name = "style_code") styleCode("style_code"),
        @Json(name = "gtin") gtin("gtin"),
        @Json(name = "lego_set") legoSet("lego_set"),
        @Json(name = "tcgplayer") tcgplayer("tcgplayer"),
        @Json(name = "discogs") discogs("discogs"),
        @Json(name = "asin") asin("asin");
    }
}

