/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param rateBps 
 * @param cents 
 * @param maturationDays 
 * @param source 
 * @param stakeBoostBps 
 * @param clamped 
 * @param tierSlug 
 * @param boostName 
 */

data class CreateCbxRateQuoteResponse (

    @Json(name = "rateBps")
    val rateBps: java.math.BigDecimal,

    @Json(name = "cents")
    val cents: java.math.BigDecimal,

    @Json(name = "maturationDays")
    val maturationDays: java.math.BigDecimal,

    @Json(name = "source")
    val source: CreateCbxRateQuoteResponse.Source,

    @Json(name = "stakeBoostBps")
    val stakeBoostBps: java.math.BigDecimal,

    @Json(name = "clamped")
    val clamped: kotlin.Boolean,

    @Json(name = "tierSlug")
    val tierSlug: kotlin.String? = null,

    @Json(name = "boostName")
    val boostName: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: tier,base,boost
     */
    enum class Source(val value: kotlin.String) {
        @Json(name = "tier") tier("tier"),
        @Json(name = "base") base("base"),
        @Json(name = "boost") boost("boost");
    }
}

