/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param suggested What we'd offer to do about this match. A suggestion for which button to  feature — never a decision. All three actions stay available.
 * @param title 
 * @param matchType 
 * @param score 0–1 confidence. Image matches report 1; title matches the similarity.
 * @param variationGroupId The variation group to ADD to, when the match already belongs to one.  Null means there is no group yet and choosing `variation` creates one from  the match plus the new listing. Without this the UI has to guess, and  guessing wrong means either a second group beside the first or a silent  no-op.
 * @param listingId The seller's existing listing this scan probably duplicates (null if the  match landed only on an inventory item with no listing row).
 * @param inventoryItemId The inventory item behind that listing, when linked. Drives the  \"View inventory\" button.
 * @param imageUrl 
 */

data class CreateListingCheckDuplicateResponseMatches (

    /* What we'd offer to do about this match. A suggestion for which button to  feature — never a decision. All three actions stay available. */
    @Json(name = "suggested")
    val suggested: CreateListingCheckDuplicateResponseMatches.Suggested,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "matchType")
    val matchType: CreateListingCheckDuplicateResponseMatches.MatchType,

    /* 0–1 confidence. Image matches report 1; title matches the similarity. */
    @Json(name = "score")
    val score: java.math.BigDecimal,

    /* The variation group to ADD to, when the match already belongs to one.  Null means there is no group yet and choosing `variation` creates one from  the match plus the new listing. Without this the UI has to guess, and  guessing wrong means either a second group beside the first or a silent  no-op. */
    @Json(name = "variationGroupId")
    val variationGroupId: kotlin.String? = null,

    /* The seller's existing listing this scan probably duplicates (null if the  match landed only on an inventory item with no listing row). */
    @Json(name = "listingId")
    val listingId: kotlin.String? = null,

    /* The inventory item behind that listing, when linked. Drives the  \"View inventory\" button. */
    @Json(name = "inventoryItemId")
    val inventoryItemId: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null

) {

    /**
     * What we'd offer to do about this match. A suggestion for which button to  feature — never a decision. All three actions stay available.
     *
     * Values: variation,restock,duplicate
     */
    enum class Suggested(val value: kotlin.String) {
        @Json(name = "variation") variation("variation"),
        @Json(name = "restock") restock("restock"),
        @Json(name = "duplicate") duplicate("duplicate");
    }
    /**
     * 
     *
     * Values: title,image
     */
    enum class MatchType(val value: kotlin.String) {
        @Json(name = "title") title("title"),
        @Json(name = "image") image("image");
    }
}

