/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param stakeId 
 * @param tierSlug 
 * @param baseUnits 
 * @param feeDiscountBps 
 * @param earnBoostBps 
 */

data class CreateCbxSubjectStakeResponse (

    @Json(name = "stakeId")
    val stakeId: kotlin.String,

    @Json(name = "tierSlug")
    val tierSlug: kotlin.String,

    @Json(name = "baseUnits")
    val baseUnits: kotlin.String,

    @Json(name = "feeDiscountBps")
    val feeDiscountBps: java.math.BigDecimal,

    @Json(name = "earnBoostBps")
    val earnBoostBps: java.math.BigDecimal

)

