/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param url 
 * @param persisted 
 * @param expiresInSeconds 
 * @param provenance 
 */

data class CreateOrderPullPlatformLabelResponse (

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "persisted")
    val persisted: kotlin.Boolean,

    @Json(name = "expiresInSeconds")
    val expiresInSeconds: java.math.BigDecimal,

    @Json(name = "provenance")
    val provenance: CreateOrderPullPlatformLabelResponse.Provenance

) {

    /**
     * 
     *
     * Values: verified,provisional
     */
    enum class Provenance(val value: kotlin.String) {
        @Json(name = "verified") verified("verified"),
        @Json(name = "provisional") provisional("provisional");
    }
}

