/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param title 
 * @param matchType 
 * @param score 0–1 confidence. Image matches report 1; title matches the similarity.
 * @param listingId The seller's existing listing this scan probably duplicates (null if the  match landed only on an inventory item with no listing row).
 * @param inventoryItemId The inventory item behind that listing, when linked. Drives the  \"View inventory\" button.
 * @param imageUrl 
 * @param variationGroupId The variation group the matched listing already belongs to, if any.    This is what turns \"you already have this\" into something useful for a  seller scanning a size run. Scan the Medium, scan the Large, and the  second scan lands here — the honest answer is usually neither \"it's the  same one\" nor \"it's different\", it's \"it's another size of that\". Which  of the two offers to make depends entirely on this field:      null      → offer to CREATE a group from the match and the new listing    set       → offer to ADD the new listing to the group that exists    Without it the UI would have to guess, and guessing wrong means either a  second group beside the first or a silent no-op.
 */

data class CreateMagicScanResponsePossibleDuplicates (

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "matchType")
    val matchType: CreateMagicScanResponsePossibleDuplicates.MatchType,

    /* 0–1 confidence. Image matches report 1; title matches the similarity. */
    @Json(name = "score")
    val score: java.math.BigDecimal,

    /* The seller's existing listing this scan probably duplicates (null if the  match landed only on an inventory item with no listing row). */
    @Json(name = "listingId")
    val listingId: kotlin.String? = null,

    /* The inventory item behind that listing, when linked. Drives the  \"View inventory\" button. */
    @Json(name = "inventoryItemId")
    val inventoryItemId: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,

    /* The variation group the matched listing already belongs to, if any.    This is what turns \"you already have this\" into something useful for a  seller scanning a size run. Scan the Medium, scan the Large, and the  second scan lands here — the honest answer is usually neither \"it's the  same one\" nor \"it's different\", it's \"it's another size of that\". Which  of the two offers to make depends entirely on this field:      null      → offer to CREATE a group from the match and the new listing    set       → offer to ADD the new listing to the group that exists    Without it the UI would have to guess, and guessing wrong means either a  second group beside the first or a silent no-op. */
    @Json(name = "variationGroupId")
    val variationGroupId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: title,image
     */
    enum class MatchType(val value: kotlin.String) {
        @Json(name = "title") title("title"),
        @Json(name = "image") image("image");
    }
}

