/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * Third-party grading read off a slab label, when the item is one.    SEPARATE FROM `condition` and never derived from it. A grade is a claim  about what a grading company certified; inferring \"PSA 10\" from a coarse  condition would be inventing an authenticity claim. It is equally never  filled from our own vision estimate (`bulk_market_items.grade`), which  ships with an explicit \"not a professional grade\" disclaimer.    Feeds eBay's Professional Grader / Grade / Certification Number condition  descriptors (synthesize/condition-descriptors.ts) and, on platforms with  no grading field, the title.
 *
 * @param graderSlug 
 * @param grade As the grader writes it: '10', '9.8', 'MS-65'.
 * @param gradeKey Derived. Never assign by hand — call `gradeKey()`.
 * @param qualifier 
 * @param sealGrade Second axis on a `dual` scale — WATA's seal grade.
 * @param certNumber 
 * @param verifiedAt 
 */

data class CreateMagicScanSynthesizeResponsePayloadGrading (

    @Json(name = "graderSlug")
    val graderSlug: kotlin.String,

    /* As the grader writes it: '10', '9.8', 'MS-65'. */
    @Json(name = "grade")
    val grade: kotlin.String,

    /* Derived. Never assign by hand — call `gradeKey()`. */
    @Json(name = "gradeKey")
    val gradeKey: kotlin.String,

    @Json(name = "qualifier")
    val qualifier: kotlin.String? = null,

    /* Second axis on a `dual` scale — WATA's seal grade. */
    @Json(name = "sealGrade")
    val sealGrade: kotlin.String? = null,

    @Json(name = "certNumber")
    val certNumber: kotlin.String? = null,

    @Json(name = "verifiedAt")
    val verifiedAt: kotlin.String? = null

)

