/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param identifierNs Where it came from, so a confirmation can be validated.
 * @param identifierValue 
 * @param title 
 * @param imageUrl 
 * @param priceCents 
 * @param storeName 
 */

data class CreateBuyerLockonObserveResponseCandidates (

    /* Where it came from, so a confirmation can be validated. */
    @Json(name = "identifierNs")
    val identifierNs: kotlin.String,

    @Json(name = "identifierValue")
    val identifierValue: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,

    @Json(name = "priceCents")
    val priceCents: java.math.BigDecimal? = null,

    @Json(name = "storeName")
    val storeName: kotlin.String? = null

)

