/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param duplicate 
 * @param cents 
 * @param boostBudgetExhausted 
 * @param accrualId 
 * @param rateBps 
 * @param maturesAt 
 */

data class CreateCbxAccrualPurchaseResponse (

    @Json(name = "duplicate")
    val duplicate: kotlin.Boolean,

    @Json(name = "cents")
    val cents: java.math.BigDecimal,

    @Json(name = "boostBudgetExhausted")
    val boostBudgetExhausted: kotlin.Boolean,

    @Json(name = "accrualId")
    val accrualId: kotlin.String? = null,

    @Json(name = "rateBps")
    val rateBps: java.math.BigDecimal? = null,

    @Json(name = "maturesAt")
    val maturesAt: kotlin.String? = null

)

