/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param code Stable across versions — branch on this, not on the message.
 * @param message Human-readable. May change.
 * @param details Optional structured context.
 */

data class ErrorError (

    /* Stable across versions — branch on this, not on the message. */
    @Json(name = "code")
    val code: kotlin.String,

    /* Human-readable. May change. */
    @Json(name = "message")
    val message: kotlin.String,

    /* Optional structured context. */
    @Json(name = "details")
    val details: kotlin.Any? = null

)

