/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetAiStatusResponseCapabilities
import net.crossly.buyer.models.GetAiStatusResponseCustomConfig

import com.squareup.moshi.Json

/**
 * 
 *
 * @param hasKey 
 * @param aiEnabled 
 * @param activeProvider 
 * @param providers 
 * @param capabilities 
 * @param customConfig 
 */

data class GetAiStatusResponse (

    @Json(name = "hasKey")
    val hasKey: kotlin.Boolean,

    @Json(name = "aiEnabled")
    val aiEnabled: kotlin.Boolean,

    @Json(name = "activeProvider")
    val activeProvider: GetAiStatusResponse.ActiveProvider,

    @Json(name = "providers")
    val providers: kotlin.Any,

    @Json(name = "capabilities")
    val capabilities: GetAiStatusResponseCapabilities,

    @Json(name = "customConfig")
    val customConfig: GetAiStatusResponseCustomConfig? = null

) {

    /**
     * 
     *
     * Values: custom,openai,anthropic,google,groq,openrouter,xai,together
     */
    enum class ActiveProvider(val value: kotlin.String) {
        @Json(name = "custom") custom("custom"),
        @Json(name = "openai") openai("openai"),
        @Json(name = "anthropic") anthropic("anthropic"),
        @Json(name = "google") google("google"),
        @Json(name = "groq") groq("groq"),
        @Json(name = "openrouter") openrouter("openrouter"),
        @Json(name = "xai") xai("xai"),
        @Json(name = "together") together("together");
    }
}

