/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param saleId 
 * @param platform 
 * @param marginPct 
 * @param detectedAt 
 * @param platformOrderId 
 * @param itemTitle 
 * @param itemBrand 
 * @param itemSku 
 * @param salePrice 
 * @param platformFee 
 * @param shippingCost 
 * @param costOfGoods 
 * @param netProfit 
 * @param daysToSell 
 */

data class GetAnalyticItemResponseItems (

    @Json(name = "saleId")
    val saleId: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "marginPct")
    val marginPct: java.math.BigDecimal,

    @Json(name = "detectedAt")
    val detectedAt: java.time.OffsetDateTime,

    @Json(name = "platformOrderId")
    val platformOrderId: kotlin.String? = null,

    @Json(name = "itemTitle")
    val itemTitle: kotlin.String? = null,

    @Json(name = "itemBrand")
    val itemBrand: kotlin.String? = null,

    @Json(name = "itemSku")
    val itemSku: kotlin.String? = null,

    @Json(name = "salePrice")
    val salePrice: java.math.BigDecimal? = null,

    @Json(name = "platformFee")
    val platformFee: java.math.BigDecimal? = null,

    @Json(name = "shippingCost")
    val shippingCost: java.math.BigDecimal? = null,

    @Json(name = "costOfGoods")
    val costOfGoods: java.math.BigDecimal? = null,

    @Json(name = "netProfit")
    val netProfit: java.math.BigDecimal? = null,

    @Json(name = "daysToSell")
    val daysToSell: java.math.BigDecimal? = null

)

