/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ordersToShip 
 * @param unreadMessages 
 * @param listingsStaleEnoughToRelist 
 * @param draftsWaiting 
 */

data class GetAnalyticTodayResponseChecklist (

    @Json(name = "ordersToShip")
    val ordersToShip: java.math.BigDecimal,

    @Json(name = "unreadMessages")
    val unreadMessages: java.math.BigDecimal,

    @Json(name = "listingsStaleEnoughToRelist")
    val listingsStaleEnoughToRelist: java.math.BigDecimal,

    @Json(name = "draftsWaiting")
    val draftsWaiting: java.math.BigDecimal

)

