/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param storeId 
 * @param host The retailer's hostname, e.g. `rei.com`.
 * @param storeName 
 * @param title 
 * @param priceCents 
 * @param currency 
 * @param url 
 * @param buyerCashbackCents What the buyer gets back, in cents, if they buy through us.  Shown because a cashback figure the buyer cannot see is a figure they have no reason to believe. Derived from the store's rate, never stored per offer — rates change and a copied one goes stale silently.
 * @param deliveredCents Item + shipping when known; item alone otherwise. See `shippingUnknown`.
 * @param shippingUnknown 
 * @param shippingCents Null = UNKNOWN, never free.
 * @param condition 
 * @param imageUrl 
 */

data class GetBuyerAnywhereResponseAlternates (

    @Json(name = "storeId")
    val storeId: kotlin.String,

    /* The retailer's hostname, e.g. `rei.com`. */
    @Json(name = "host")
    val host: kotlin.String,

    @Json(name = "storeName")
    val storeName: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "priceCents")
    val priceCents: java.math.BigDecimal,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    /* What the buyer gets back, in cents, if they buy through us.  Shown because a cashback figure the buyer cannot see is a figure they have no reason to believe. Derived from the store's rate, never stored per offer — rates change and a copied one goes stale silently. */
    @Json(name = "buyerCashbackCents")
    val buyerCashbackCents: java.math.BigDecimal,

    /* Item + shipping when known; item alone otherwise. See `shippingUnknown`. */
    @Json(name = "deliveredCents")
    val deliveredCents: java.math.BigDecimal,

    @Json(name = "shippingUnknown")
    val shippingUnknown: kotlin.Boolean,

    /* Null = UNKNOWN, never free. */
    @Json(name = "shippingCents")
    val shippingCents: java.math.BigDecimal? = null,

    @Json(name = "condition")
    val condition: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null

)

