/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param slug 
 * @param title 
 * @param priceCents 
 * @param currency 
 * @param url 
 * @param condition 
 * @param imageUrl 
 */

data class GetBuyerAnywhereResponseCrossly (

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "priceCents")
    val priceCents: java.math.BigDecimal,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "condition")
    val condition: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null

)

