/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param grantedBaseUnits 
 * @param earnedBaseUnits 
 * @param stakedBaseUnits 
 * @param earnedAvailableBaseUnits 
 * @param connectedAvailableBaseUnits 
 * @param totalSpendableBaseUnits 
 */

data class GetCbxSubjectBalanceBySubjectIdResponse (

    @Json(name = "grantedBaseUnits")
    val grantedBaseUnits: kotlin.String,

    @Json(name = "earnedBaseUnits")
    val earnedBaseUnits: kotlin.String,

    @Json(name = "stakedBaseUnits")
    val stakedBaseUnits: kotlin.String,

    @Json(name = "earnedAvailableBaseUnits")
    val earnedAvailableBaseUnits: kotlin.String,

    @Json(name = "connectedAvailableBaseUnits")
    val connectedAvailableBaseUnits: kotlin.String,

    @Json(name = "totalSpendableBaseUnits")
    val totalSpendableBaseUnits: kotlin.String

)

