/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * What the browser itself last reported, when it has reported at all.
 *
 * @param observations 
 * @param cookieCount 
 * @param observedAt 
 * @param observedAgo 
 * @param extensionVersion 
 */

data class GetConnectionHealthResponseBrowser (

    @Json(name = "observations")
    val observations: kotlin.collections.List<kotlin.Any>,

    @Json(name = "cookieCount")
    val cookieCount: java.math.BigDecimal,

    @Json(name = "observedAt")
    val observedAt: kotlin.String,

    @Json(name = "observedAgo")
    val observedAgo: kotlin.String,

    @Json(name = "extensionVersion")
    val extensionVersion: kotlin.String? = null

)

