/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param balanceBaseUnits 
 * @param stakedBaseUnits 
 * @param availableBaseUnits 
 * @param feeDiscountBps 
 * @param earnBoostBps 
 * @param tierSlug 
 * @param status 
 * @param unlocksAt 
 */

data class GetCbxSubjectStakeResponse (

    @Json(name = "balanceBaseUnits")
    val balanceBaseUnits: kotlin.String,

    @Json(name = "stakedBaseUnits")
    val stakedBaseUnits: kotlin.String,

    @Json(name = "availableBaseUnits")
    val availableBaseUnits: kotlin.String,

    @Json(name = "feeDiscountBps")
    val feeDiscountBps: java.math.BigDecimal,

    @Json(name = "earnBoostBps")
    val earnBoostBps: java.math.BigDecimal,

    @Json(name = "tierSlug")
    val tierSlug: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "unlocksAt")
    val unlocksAt: kotlin.String? = null

)

