/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param claimId 
 * @param status 
 * @param requestedBaseUnits 
 * @param netBaseUnits 
 * @param attempts 
 * @param createdAt 
 * @param txSig 
 * @param failureReason 
 * @param confirmedAt 
 */

data class GetCbxClaimResponse (

    @Json(name = "claimId")
    val claimId: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "requestedBaseUnits")
    val requestedBaseUnits: kotlin.String,

    @Json(name = "netBaseUnits")
    val netBaseUnits: kotlin.String,

    @Json(name = "attempts")
    val attempts: java.math.BigDecimal,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "txSig")
    val txSig: kotlin.String? = null,

    @Json(name = "failureReason")
    val failureReason: kotlin.String? = null,

    @Json(name = "confirmedAt")
    val confirmedAt: java.time.OffsetDateTime? = null

)

