/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetCustomerResponseContactAddress

import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param name 
 * @param phone 
 * @param address 
 * @param addressPlatform Where the address came from, so the UI can say.
 */

data class GetCustomerResponseContact (

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "address")
    val address: GetCustomerResponseContactAddress? = null,

    /* Where the address came from, so the UI can say. */
    @Json(name = "addressPlatform")
    val addressPlatform: kotlin.String? = null

)

