/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetConnectionEmailResponseData
import net.crossly.buyer.models.GetConnectionEmailResponseOauth

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param imap 
 * @param oauth 
 */

data class GetConnectionEmailResponse (

    @Json(name = "data")
    val `data`: kotlin.collections.List<GetConnectionEmailResponseData>,

    @Json(name = "imap")
    val imap: kotlin.collections.List<GetConnectionEmailResponseData>,

    @Json(name = "oauth")
    val oauth: kotlin.collections.List<GetConnectionEmailResponseOauth>

)

