/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param sentAt 
 * @param conversationId 
 * @param sender 
 * @param videoUrl 
 * @param syncedAt 
 * @param body 
 * @param platformMessageId 
 * @param attachments 
 * @param aiIntent 
 * @param aiUrgency 
 * @param aiScamScore 
 * @param aiSuggestedReply 
 * @param aiTriagedAt 
 * @param stickerId 
 * @param gifUrl 
 * @param videoThumbUrl 
 * @param voiceUrl 
 * @param voiceDurationSeconds 
 */

data class GetInboxResponseMessages (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "sentAt")
    val sentAt: java.time.OffsetDateTime,

    @Json(name = "conversationId")
    val conversationId: kotlin.String,

    @Json(name = "sender")
    val sender: kotlin.String,

    @Json(name = "videoUrl")
    val videoUrl: kotlin.String? = null,

    @Json(name = "syncedAt")
    val syncedAt: java.time.OffsetDateTime? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "platformMessageId")
    val platformMessageId: kotlin.String? = null,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "aiIntent")
    val aiIntent: kotlin.String? = null,

    @Json(name = "aiUrgency")
    val aiUrgency: kotlin.String? = null,

    @Json(name = "aiScamScore")
    val aiScamScore: java.math.BigDecimal? = null,

    @Json(name = "aiSuggestedReply")
    val aiSuggestedReply: kotlin.String? = null,

    @Json(name = "aiTriagedAt")
    val aiTriagedAt: java.time.OffsetDateTime? = null,

    @Json(name = "stickerId")
    val stickerId: kotlin.String? = null,

    @Json(name = "gifUrl")
    val gifUrl: kotlin.String? = null,

    @Json(name = "videoThumbUrl")
    val videoThumbUrl: kotlin.String? = null,

    @Json(name = "voiceUrl")
    val voiceUrl: kotlin.String? = null,

    @Json(name = "voiceDurationSeconds")
    val voiceDurationSeconds: java.math.BigDecimal? = null

)

