/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param label 
 * @param sortKey 
 * @param tradesCount 
 * @param skuId 
 * @param externalId 
 * @param externalSource 
 * @param externalSyncedAt 
 * @param lastSaleCents 
 * @param lastSaleAt 
 * @param bestBidCents 
 * @param bestAskCents 
 */

data class GetMarketProductResponseVariants (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "sortKey")
    val sortKey: java.math.BigDecimal,

    @Json(name = "tradesCount")
    val tradesCount: java.math.BigDecimal,

    @Json(name = "skuId")
    val skuId: kotlin.String,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "externalSource")
    val externalSource: kotlin.String? = null,

    @Json(name = "externalSyncedAt")
    val externalSyncedAt: java.time.OffsetDateTime? = null,

    @Json(name = "lastSaleCents")
    val lastSaleCents: java.math.BigDecimal? = null,

    @Json(name = "lastSaleAt")
    val lastSaleAt: java.time.OffsetDateTime? = null,

    @Json(name = "bestBidCents")
    val bestBidCents: java.math.BigDecimal? = null,

    @Json(name = "bestAskCents")
    val bestAskCents: java.math.BigDecimal? = null

)

