/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetMarketVariantBookResponseBids

import com.squareup.moshi.Json

/**
 * 
 *
 * @param condition 
 * @param bids 
 * @param asks 
 * @param gradeKey 
 */

data class GetMarketVariantBookResponse (

    @Json(name = "condition")
    val condition: kotlin.String,

    @Json(name = "bids")
    val bids: kotlin.collections.List<GetMarketVariantBookResponseBids>,

    @Json(name = "asks")
    val asks: kotlin.collections.List<GetMarketVariantBookResponseBids>,

    @Json(name = "gradeKey")
    val gradeKey: kotlin.String? = null

)

