/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetOauthInitResponseOneOf
import net.crossly.buyer.models.GetOauthInitResponseOneOf1
import net.crossly.buyer.models.GetOauthInitResponseOneOf2
import net.crossly.buyer.models.GetOauthInitResponseOneOf3

import com.squareup.moshi.Json

/**
 * 
 *
 * @param url 
 * @param correlationId 
 * @param oneShot 
 * @param status 
 * @param requestUrl 
 * @param message 
 */

data class GetOauthInitResponse (

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "correlationId")
    val correlationId: kotlin.String,

    @Json(name = "oneShot")
    val oneShot: kotlin.Boolean,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "requestUrl")
    val requestUrl: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String

)

