/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param status 
 * @param amountCents 
 * @param isBundle 
 * @param items 
 * @param expiresAt 
 * @param createdAt 
 * @param listedTotalCents Asking total when the offer was made — what the buyer responded to.
 * @param message 
 * @param parentOfferId 
 * @param decidedAt 
 * @param consumedAt Set once an accepted offer has actually been paid for.
 */

data class GetOfferResponseOffers (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "amountCents")
    val amountCents: java.math.BigDecimal,

    @Json(name = "isBundle")
    val isBundle: kotlin.Boolean,

    @Json(name = "items")
    val items: kotlin.collections.List<kotlin.Any>,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Asking total when the offer was made — what the buyer responded to. */
    @Json(name = "listedTotalCents")
    val listedTotalCents: java.math.BigDecimal? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "parentOfferId")
    val parentOfferId: kotlin.String? = null,

    @Json(name = "decidedAt")
    val decidedAt: java.time.OffsetDateTime? = null,

    /* Set once an accepted offer has actually been paid for. */
    @Json(name = "consumedAt")
    val consumedAt: java.time.OffsetDateTime? = null

)

