/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key 
 * @param points 
 * @param detail Shown to the seller verbatim. Must read as a fact, not a verdict.
 */

data class GetOrderEvidenceResponseGradeSignals (

    @Json(name = "key")
    val key: GetOrderEvidenceResponseGradeSignals.Key,

    @Json(name = "points")
    val points: java.math.BigDecimal,

    /* Shown to the seller verbatim. Must read as a fact, not a verdict. */
    @Json(name = "detail")
    val detail: kotlin.String

) {

    /**
     * 
     *
     * Values: packingCapture,continuousTake,sealVerified,serialPreRecorded,serialSeenOnFrame,arrivalCondition
     */
    enum class Key(val value: kotlin.String) {
        @Json(name = "packing_capture") packingCapture("packing_capture"),
        @Json(name = "continuous_take") continuousTake("continuous_take"),
        @Json(name = "seal_verified") sealVerified("seal_verified"),
        @Json(name = "serial_pre_recorded") serialPreRecorded("serial_pre_recorded"),
        @Json(name = "serial_seen_on_frame") serialSeenOnFrame("serial_seen_on_frame"),
        @Json(name = "arrival_condition") arrivalCondition("arrival_condition");
    }
}

