/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param state 
 * @param windowHours 
 * @param detail 
 * @param photos 
 * @param requestedAt 
 * @param closesAt When the window shuts. Null when nothing was ever asked.
 */

data class GetOrderEvidenceResponseArrival (

    @Json(name = "state")
    val state: GetOrderEvidenceResponseArrival.State,

    @Json(name = "windowHours")
    val windowHours: java.math.BigDecimal,

    @Json(name = "detail")
    val detail: kotlin.String,

    @Json(name = "photos")
    val photos: kotlin.collections.List<kotlin.String>,

    @Json(name = "requestedAt")
    val requestedAt: java.time.OffsetDateTime? = null,

    /* When the window shuts. Null when nothing was ever asked. */
    @Json(name = "closesAt")
    val closesAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: notRequested,awaiting,submitted,declined,windowClosed
     */
    enum class State(val value: kotlin.String) {
        @Json(name = "not_requested") notRequested("not_requested"),
        @Json(name = "awaiting") awaiting("awaiting"),
        @Json(name = "submitted") submitted("submitted"),
        @Json(name = "declined") declined("declined"),
        @Json(name = "window_closed") windowClosed("window_closed");
    }
}

