/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.GetOrderEvidenceResponseGradeSignals

import com.squareup.moshi.Json

/**
 * 
 *
 * @param grade 
 * @param points 
 * @param signals 
 * @param nextStep The single most valuable thing not yet done, phrased as an action.  One, not a checklist. A seller given six things to fix does none of them; a seller given the one worth the most does that one.
 */

data class GetOrderEvidenceResponseGrade (

    @Json(name = "grade")
    val grade: GetOrderEvidenceResponseGrade.Grade,

    @Json(name = "points")
    val points: java.math.BigDecimal,

    @Json(name = "signals")
    val signals: kotlin.collections.List<GetOrderEvidenceResponseGradeSignals>,

    /* The single most valuable thing not yet done, phrased as an action.  One, not a checklist. A seller given six things to fix does none of them; a seller given the one worth the most does that one. */
    @Json(name = "nextStep")
    val nextStep: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: none,strong,basic,conclusive
     */
    enum class Grade(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "strong") strong("strong"),
        @Json(name = "basic") basic("basic"),
        @Json(name = "conclusive") conclusive("conclusive");
    }
}

