/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * eBay-imposed monthly selling cap (quantity + $$) fetched from Trading API GetMyeBaySelling. These are HARD blocks — past them, `publishOffer` returns an error. Distinct from the free-tier `limit` (which is just a fee threshold). Null when seller has no caps (established accounts) or the Trading call failed.
 *
 * @param currency 
 * @param fetchedAt ISO timestamp this was fetched (used for cache freshness display).
 * @param amountLimit Monthly $$ ceiling — null when seller has no $$ cap set.
 * @param amountUsed 
 * @param quantityLimit Monthly item-count ceiling — null when seller has no qty cap.
 * @param quantityUsed 
 */

data class GetPlatformLimitResponseEbaySellingCap (

    @Json(name = "currency")
    val currency: kotlin.String,

    /* ISO timestamp this was fetched (used for cache freshness display). */
    @Json(name = "fetchedAt")
    val fetchedAt: kotlin.String,

    /* Monthly $$ ceiling — null when seller has no $$ cap set. */
    @Json(name = "amountLimit")
    val amountLimit: java.math.BigDecimal? = null,

    @Json(name = "amountUsed")
    val amountUsed: java.math.BigDecimal? = null,

    /* Monthly item-count ceiling — null when seller has no qty cap. */
    @Json(name = "quantityLimit")
    val quantityLimit: java.math.BigDecimal? = null,

    @Json(name = "quantityUsed")
    val quantityUsed: java.math.BigDecimal? = null

)

