/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key 
 * @param index 
 * @param label 
 * @param groupPath Group path this container primarily holds, for signage on the object.
 * @param capacity 
 * @param used 
 */

data class GetSpatialPublicResponseSolvedContainers (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "index")
    val index: java.math.BigDecimal,

    @Json(name = "label")
    val label: kotlin.String,

    /* Group path this container primarily holds, for signage on the object. */
    @Json(name = "groupPath")
    val groupPath: kotlin.collections.List<kotlin.String>,

    @Json(name = "capacity")
    val capacity: java.math.BigDecimal,

    @Json(name = "used")
    val used: java.math.BigDecimal

)

