/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param key 
 * @param label 
 * @param master 
 * @param required 
 * @param dataType 
 * @param hasEnumValues 
 * @param enumValues 
 * @param hint 
 */

data class GetTaxonomyRequiredFieldResponseRequiredFields (

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "master")
    val master: kotlin.Boolean,

    @Json(name = "required")
    val required: kotlin.Boolean,

    @Json(name = "dataType")
    val dataType: GetTaxonomyRequiredFieldResponseRequiredFields.DataType,

    @Json(name = "hasEnumValues")
    val hasEnumValues: kotlin.Boolean,

    @Json(name = "enumValues")
    val enumValues: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "hint")
    val hint: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: sTRING,nUMBER,bOOLEAN
     */
    enum class DataType(val value: kotlin.String) {
        @Json(name = "STRING") sTRING("STRING"),
        @Json(name = "NUMBER") nUMBER("NUMBER"),
        @Json(name = "BOOLEAN") bOOLEAN("BOOLEAN");
    }
}

