/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param capabilities 
 * @param createdAt 
 * @param id 
 * @param name 
 * @param lastSeenAt 
 * @param os 
 * @param version 
 */

data class ListDevicesItem (

    @Json(name = "capabilities")
    val capabilities: kotlin.collections.List<kotlin.String>,

    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "lastSeenAt")
    val lastSeenAt: kotlin.String? = null,

    @Json(name = "os")
    val os: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

)

