/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param label 
 * @param condition 
 * @param openAsks 
 * @param openBids 
 * @param tradesCount 
 * @param gradeKey null = ungraded, which is the tier every pre-grading order sits in.
 * @param lowestAskCents 
 * @param highestBidCents 
 * @param lastSaleCents 
 * @param lastSaleAt 
 */

data class ListMarketVariantTiersItem (

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "condition")
    val condition: kotlin.String,

    @Json(name = "openAsks")
    val openAsks: java.math.BigDecimal,

    @Json(name = "openBids")
    val openBids: java.math.BigDecimal,

    @Json(name = "tradesCount")
    val tradesCount: java.math.BigDecimal,

    /* null = ungraded, which is the tier every pre-grading order sits in. */
    @Json(name = "gradeKey")
    val gradeKey: kotlin.String? = null,

    @Json(name = "lowestAskCents")
    val lowestAskCents: java.math.BigDecimal? = null,

    @Json(name = "highestBidCents")
    val highestBidCents: java.math.BigDecimal? = null,

    @Json(name = "lastSaleCents")
    val lastSaleCents: java.math.BigDecimal? = null,

    @Json(name = "lastSaleAt")
    val lastSaleAt: java.time.OffsetDateTime? = null

)

