/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param available 
 * @param id 
 * @param platformListingId 
 * @param quantity 
 * @param unitPriceCents 
 * @param slug 
 * @param title 
 * @param listingStatus 
 */

data class ListBuyerCartItem (

    @Json(name = "available")
    val available: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "platformListingId")
    val platformListingId: kotlin.String,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    @Json(name = "unitPriceCents")
    val unitPriceCents: java.math.BigDecimal,

    @Json(name = "slug")
    val slug: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "listingStatus")
    val listingStatus: kotlin.String? = null

)

