/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param categorySlug 
 * @param tradesCount 
 * @param gradedGradeKeys 
 * @param brand 
 * @param model 
 * @param styleCode 
 * @param imageUrl 
 * @param lowestAskCentsFrom 
 * @param highestBidCents 
 * @param lastSaleCents 
 */

data class ListMarketProductsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "categorySlug")
    val categorySlug: kotlin.String,

    @Json(name = "tradesCount")
    val tradesCount: java.math.BigDecimal,

    @Json(name = "gradedGradeKeys")
    val gradedGradeKeys: kotlin.collections.List<kotlin.String>,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "model")
    val model: kotlin.String? = null,

    @Json(name = "styleCode")
    val styleCode: kotlin.String? = null,

    @Json(name = "imageUrl")
    val imageUrl: kotlin.String? = null,

    @Json(name = "lowestAskCentsFrom")
    val lowestAskCentsFrom: java.math.BigDecimal? = null,

    @Json(name = "highestBidCents")
    val highestBidCents: java.math.BigDecimal? = null,

    @Json(name = "lastSaleCents")
    val lastSaleCents: java.math.BigDecimal? = null

)

