/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param prefix 
 * @param scopes 
 * @param environment 
 * @param createdAt 
 * @param lastUsedAt 
 * @param expiresAt 
 * @param revokedAt 
 */

data class ListPatItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "prefix")
    val prefix: kotlin.String,

    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @Json(name = "environment")
    val environment: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "lastUsedAt")
    val lastUsedAt: java.time.OffsetDateTime? = null,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Json(name = "revokedAt")
    val revokedAt: java.time.OffsetDateTime? = null

)

