/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.ListInventoryUnitsItemIdentifiers

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param status 
 * @param createdAt 
 * @param identifiers 
 * @param orderId 
 * @param soldAt 
 * @param notes 
 */

data class ListInventoryUnitsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "identifiers")
    val identifiers: kotlin.collections.List<ListInventoryUnitsItemIdentifiers>,

    @Json(name = "orderId")
    val orderId: kotlin.String? = null,

    @Json(name = "soldAt")
    val soldAt: java.time.OffsetDateTime? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null

)

