/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param platform 
 * @param accountSlot 
 * @param status 
 * @param createdAt 
 * @param label 
 * @param platformUsername 
 * @param lastSyncedAt 
 */

data class ListAccountsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "accountSlot")
    val accountSlot: java.math.BigDecimal,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "platformUsername")
    val platformUsername: kotlin.String? = null,

    @Json(name = "lastSyncedAt")
    val lastSyncedAt: java.time.OffsetDateTime? = null

)

