/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param slug 
 * @param name 
 * @param categorySlugs 
 * @param scale 
 * @param grades 
 * @param qualifiers 
 * @param sealGrades 
 */

data class ListMarketGradersItem (

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "categorySlugs")
    val categorySlugs: kotlin.collections.List<kotlin.String>,

    @Json(name = "scale")
    val scale: ListMarketGradersItem.Scale,

    @Json(name = "grades")
    val grades: kotlin.collections.List<kotlin.String>,

    @Json(name = "qualifiers")
    val qualifiers: kotlin.collections.List<kotlin.String>,

    @Json(name = "sealGrades")
    val sealGrades: kotlin.collections.List<kotlin.String>

) {

    /**
     * 
     *
     * Values: numeric,sheldon,dual,hundred
     */
    enum class Scale(val value: kotlin.String) {
        @Json(name = "numeric") numeric("numeric"),
        @Json(name = "sheldon") sheldon("sheldon"),
        @Json(name = "dual") dual("dual"),
        @Json(name = "hundred") hundred("hundred");
    }
}

