/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param platform 
 * @param isActive 
 * @param shopUrl 
 * @param lastSeenActive 
 * @param tokenExpiresAt 
 * @param createdAt 
 */

data class ListConnectionsItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "isActive")
    val isActive: kotlin.Boolean,

    @Json(name = "shopUrl")
    val shopUrl: kotlin.String? = null,

    @Json(name = "lastSeenActive")
    val lastSeenActive: java.time.OffsetDateTime? = null,

    @Json(name = "tokenExpiresAt")
    val tokenExpiresAt: java.time.OffsetDateTime? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

