/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param userId 
 * @param status 
 * @param platform 
 * @param accountSlot 
 * @param platformConversationId 
 * @param isRead 
 * @param isHidden 
 * @param hasOffer 
 * @param listingId 
 * @param inventoryItemId 
 * @param buyerUsername 
 * @param subject 
 * @param buyerPlatformId 
 * @param offerAmount 
 * @param offerStatus 
 * @param platformConversationUrl 
 * @param lastMessageAt 
 */

data class ListInboxItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "userId")
    val userId: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "platform")
    val platform: kotlin.String,

    @Json(name = "accountSlot")
    val accountSlot: java.math.BigDecimal,

    @Json(name = "platformConversationId")
    val platformConversationId: kotlin.String,

    @Json(name = "isRead")
    val isRead: kotlin.Boolean,

    @Json(name = "isHidden")
    val isHidden: kotlin.Boolean,

    @Json(name = "hasOffer")
    val hasOffer: kotlin.Boolean,

    @Json(name = "listingId")
    val listingId: kotlin.String? = null,

    @Json(name = "inventoryItemId")
    val inventoryItemId: kotlin.String? = null,

    @Json(name = "buyerUsername")
    val buyerUsername: kotlin.String? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "buyerPlatformId")
    val buyerPlatformId: kotlin.String? = null,

    @Json(name = "offerAmount")
    val offerAmount: kotlin.String? = null,

    @Json(name = "offerStatus")
    val offerStatus: kotlin.String? = null,

    @Json(name = "platformConversationUrl")
    val platformConversationUrl: kotlin.String? = null,

    @Json(name = "lastMessageAt")
    val lastMessageAt: java.time.OffsetDateTime? = null

)

