/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models

import net.crossly.buyer.models.ListInventoryItemCategory

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param updatedAt 
 * @param userId 
 * @param quantity 
 * @param quantityAvailable 
 * @param quantityReserved 
 * @param quantitySold 
 * @param color 
 * @param defaultTitle 
 * @param images 
 * @param tags 
 * @param labels 
 * @param includeTaxInLanded 
 * @param floorIsNet 
 * @param status 
 * @param source 
 * @param brand 
 * @param sku 
 * @param originalPrice 
 * @param condition 
 * @param propertySize 
 * @param material 
 * @param style 
 * @param pattern 
 * @param department 
 * @param gender 
 * @param itemType 
 * @param sizeSystem 
 * @param videoUrl 
 * @param notes 
 * @param customLabel 
 * @param warehouseLocation 
 * @param storageBin 
 * @param storageNote 
 * @param marketSkuId 
 * @param marketVariantId 
 * @param firstListedAt 
 * @param costBasisCents 
 * @param priceFloorCents 
 * @param acquiredAt 
 * @param acquiredSource 
 * @param weightLb 
 * @param weightOz 
 * @param dimensionLIn 
 * @param dimensionWIn 
 * @param dimensionHIn 
 * @param category 
 */

data class ListInventoryItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "userId")
    val userId: kotlin.String,

    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    @Json(name = "quantityAvailable")
    val quantityAvailable: java.math.BigDecimal,

    @Json(name = "quantityReserved")
    val quantityReserved: java.math.BigDecimal,

    @Json(name = "quantitySold")
    val quantitySold: java.math.BigDecimal,

    @Json(name = "color")
    val color: kotlin.collections.List<kotlin.String>,

    @Json(name = "defaultTitle")
    val defaultTitle: kotlin.String,

    @Json(name = "images")
    val images: kotlin.collections.List<kotlin.String>,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "labels")
    val labels: kotlin.collections.List<kotlin.String>,

    @Json(name = "includeTaxInLanded")
    val includeTaxInLanded: kotlin.Boolean,

    @Json(name = "floorIsNet")
    val floorIsNet: kotlin.Boolean,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "source")
    val source: kotlin.String,

    @Json(name = "brand")
    val brand: kotlin.String? = null,

    @Json(name = "sku")
    val sku: kotlin.String? = null,

    @Json(name = "originalPrice")
    val originalPrice: kotlin.String? = null,

    @Json(name = "condition")
    val condition: kotlin.String? = null,

    @Json(name = "size")
    val propertySize: kotlin.String? = null,

    @Json(name = "material")
    val material: kotlin.String? = null,

    @Json(name = "style")
    val style: kotlin.String? = null,

    @Json(name = "pattern")
    val pattern: kotlin.String? = null,

    @Json(name = "department")
    val department: kotlin.String? = null,

    @Json(name = "gender")
    val gender: kotlin.String? = null,

    @Json(name = "itemType")
    val itemType: kotlin.String? = null,

    @Json(name = "sizeSystem")
    val sizeSystem: kotlin.String? = null,

    @Json(name = "videoUrl")
    val videoUrl: kotlin.String? = null,

    @Json(name = "notes")
    val notes: kotlin.String? = null,

    @Json(name = "customLabel")
    val customLabel: kotlin.String? = null,

    @Json(name = "warehouseLocation")
    val warehouseLocation: kotlin.String? = null,

    @Json(name = "storageBin")
    val storageBin: kotlin.String? = null,

    @Json(name = "storageNote")
    val storageNote: kotlin.String? = null,

    @Json(name = "marketSkuId")
    val marketSkuId: kotlin.String? = null,

    @Json(name = "marketVariantId")
    val marketVariantId: kotlin.String? = null,

    @Json(name = "firstListedAt")
    val firstListedAt: java.time.OffsetDateTime? = null,

    @Json(name = "costBasisCents")
    val costBasisCents: java.math.BigDecimal? = null,

    @Json(name = "priceFloorCents")
    val priceFloorCents: java.math.BigDecimal? = null,

    @Json(name = "acquiredAt")
    val acquiredAt: java.time.OffsetDateTime? = null,

    @Json(name = "acquiredSource")
    val acquiredSource: kotlin.String? = null,

    @Json(name = "weightLb")
    val weightLb: kotlin.String? = null,

    @Json(name = "weightOz")
    val weightOz: kotlin.String? = null,

    @Json(name = "dimensionLIn")
    val dimensionLIn: kotlin.String? = null,

    @Json(name = "dimensionWIn")
    val dimensionWIn: kotlin.String? = null,

    @Json(name = "dimensionHIn")
    val dimensionHIn: kotlin.String? = null,

    @Json(name = "category")
    val category: ListInventoryItemCategory? = null

)

