/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param listingId 
 * @param sortKey 
 * @param status 
 * @param quantityAvailable 
 * @param axisValue 
 * @param title 
 * @param price 
 * @param images 
 * @param sku 
 */

data class ListVariationGroupsItemMembers (

    @Json(name = "listingId")
    val listingId: kotlin.String,

    @Json(name = "sortKey")
    val sortKey: java.math.BigDecimal,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "quantityAvailable")
    val quantityAvailable: java.math.BigDecimal,

    @Json(name = "axisValue")
    val axisValue: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "price")
    val price: kotlin.String? = null,

    @Json(name = "images")
    val images: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "sku")
    val sku: kotlin.String? = null

)

