/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.crossly.buyer.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param patId 
 * @param enabled 
 * @param dailyLimitCents 
 * @param perOrderLimitCents 
 * @param maxUnitsPerListingPerDay 
 */

data class UpdateBuyerCheckoutControlResponse (

    @Json(name = "patId")
    val patId: kotlin.String,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "dailyLimitCents")
    val dailyLimitCents: java.math.BigDecimal,

    @Json(name = "perOrderLimitCents")
    val perOrderLimitCents: java.math.BigDecimal,

    @Json(name = "maxUnitsPerListingPerDay")
    val maxUnitsPerListingPerDay: java.math.BigDecimal

)

